name: Python Build

on:
  push:
    paths:
    - 'python/**'
    - 'src/**'
    - '.github/workflows/python_test.yml'
    - "!python/.gitignore"
    - "!python/pytest/**"
  pull_request:
    paths:
    - 'python/**'
    - 'src/**'
    - '.github/workflows/python_test.yml'
    - "!python/.gitignore"
    - "!python/pytest/**"
  workflow_dispatch:

jobs:
  Install-Test:
    name: Installation test for python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python --version
          pip install pybind11[global]
      - name: Install abess
        run: |
          cd ./python
          pip install . -v
      - name: A simple test
        run: |
          echo "import abess; print(abess.__version__);" > ./test.py
          python ./test.py
